enhence and fix some bugs in user-management module
Mahmoudgalalz/crcl-service pull request #1
Opened 2024-09-30 13:56 UTC by haithamAbuElnasr

Hello Kro,

I've made some enhancements to the user management module. Please let me know if there's anything you'd like me to add or adjust.

2024-09-30 15:26 UTC, Mahmoudgalalz commented on src/services/user/user.controller.ts
>    }
this user controller is outdated it will be removed

2024-09-30 15:26 UTC, Mahmoudgalalz commented on src/services/users-management/dto/create-admin.dto.ts
> +  })
good correction for the decoretores

2024-09-30 15:28 UTC, Mahmoudgalalz commented on src/shared/interface/roles.ts
> +  SuperAdmin = 'SUPER_ADMIN',
!!!! why, what is the refernece for it?

your branch is has huge diversion

2024-09-30 15:30 UTC, Mahmoudgalalz commented on src/shared/interface/roles.ts
> +  SuperAdmin = 'SUPER_ADMIN',
export enum Role {
  Admin = 'ADMIN',
  User = 'USER',
  Reader = 'READER',
  Booth = 'BOOTH',
}

2024-09-30 15:34 UTC, Mahmoudgalalz commented on src/services/users-management/user-management.controller.ts
> +    const pageNumber = parseInt(page, 10) || 1;  // Convert to number and apply default
remove the fallback, its already dublicated, each value has a default already.

remove comments that is already known

2024-09-30 21:25 UTC, Mahmoudgalalz requested changes

2024-09-30 21:25 UTC, Mahmoudgalalz commented on src/services/users-management/user-management.controller.ts
> +/* eslint-disable prettier/prettier */
remove all these lines

2024-09-30 21:25 UTC, Mahmoudgalalz commented on src/services/users-management/user-management.controller.ts
> +  @Roles(Role.SuperAdmin)
this has been set as a global, so its duplicated

2024-09-30 21:25 UTC, Mahmoudgalalz commented on src/services/users-management/user-management.controller.ts
>    }
the version I have its surrounded by try-catch block

2024-10-01 07:33 UTC, haithamAbuElnasr commented on src/services/users-management/user-management.controller.ts
> +/* eslint-disable prettier/prettier */
I can't work without it for now i still have that formmting problem

2024-10-01 07:34 UTC, haithamAbuElnasr commented on src/services/users-management/user-management.controller.ts
> +  @Roles(Role.SuperAdmin)
if you mean @Roles(Role.SuperAdmin) this is SuperAdmin not just  Admin .

2024-10-01 07:37 UTC, haithamAbuElnasr commented on src/services/users-management/user-management.controller.ts
>    }
I belive it's surrounded  in the last commit already!

2024-10-01 19:53 UTC, closed without merging