Enhance auth module
Mahmoudgalalz/crcl-service pull request #14
Opened 2024-10-02 23:42 UTC by haithamAbuElnasr

check the thing have to be edit before i work reg-module

2024-10-02 23:57 UTC, Mahmoudgalalz requested changes

2024-10-02 23:57 UTC, Mahmoudgalalz commented on package.json
> +    "crcl-service": "file:",
Why this !

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/app.module.ts
> +    RedisModule,
Dont needed to be a module, its only a service and configered as async

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/common/init.data.ts
> +import * as bcrypt from 'bcrypt';
Huge bundle, but will skip it

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/common/init.data.ts
> +        password: await hashPassword(password),
Then please consider this validation in prisma/seed.ts file too

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/auth/auth.controller.ts
> +      return new SuccessResponse('Token', { access_token: user });
You made a encryption for the root user and left the user 🥲

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/auth/auth.service.ts
> +    console.log(user);
Remove

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/auth/auth.service.ts
> +    if (user && (await this.comparePassword(pass, user.password))) {
Put the function out side store it in a var it safe

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/otp/otp.module.ts
> +@Module({
This is why we dont need a module 😗😉

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/redis/redis.module.ts
> +  providers: [
You can register this globle in the app module

2024-10-02 23:57 UTC, Mahmoudgalalz commented on src/shared/redis/redis.module.ts
> +export class RedisModule {}
And remove the module all

2024-10-03 00:00 UTC, haithamAbuElnasr commented on package.json
> +    "crcl-service": "file:",
idk

2024-10-03 00:06 UTC, haithamAbuElnasr commented on src/shared/redis/redis.module.ts
> +  providers: [
I don't understand!

2024-10-03 00:07 UTC, haithamAbuElnasr commented on src/shared/auth/auth.controller.ts
> +      return new SuccessResponse('Token', { access_token: user });
it 's in the service!!

2024-10-03 00:17 UTC, Mahmoudgalalz commented on package.json
> +    "crcl-service": "file:",
Remove it

2024-10-03 00:18 UTC, Mahmoudgalalz commented on src/shared/auth/auth.controller.ts
> +      return new SuccessResponse('Token', { access_token: user });
Then why the other one in the controller 
Be consistent

2024-10-03 00:18 UTC, Mahmoudgalalz commented on src/shared/redis/redis.module.ts
> +  providers: [
Look for the prisma service, how it works

2024-10-03 00:45 UTC, haithamAbuElnasr commented on src/shared/auth/auth.controller.ts
> +      return new SuccessResponse('Token', { access_token: user });
no all in  the service the other one in the init.ts

2024-10-03 00:57 UTC, haithamAbuElnasr commented on package.json
> +    "crcl-service": "file:",
solved

2024-10-03 00:57 UTC, haithamAbuElnasr commented on src/app.module.ts
> +    RedisModule,
solved

2024-10-03 00:58 UTC, haithamAbuElnasr commented on src/common/init.data.ts
> +        password: await hashPassword(password),
it's huge work

2024-10-03 00:58 UTC, haithamAbuElnasr commented on src/shared/auth/auth.service.ts
> +    console.log(user);
solved

2024-10-04 15:51 UTC, Mahmoudgalalz requested changes

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/common/init.data.ts
>      }
I don't need to compare password here, if user exist ignore, this is a layer of backdoor not for the app,

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/shared/auth/shared/otp.service.ts
> +    const otp = crypto.randomInt(100000, 999999).toString();
use the nanoid in the unique-id in the utilities, 

create a new customAlph with 0123456789, and opt-out 4 char from it

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/shared/auth/registration.service.ts
> +        });
its good, but we need also to send the refresh token, look at the admin/login endpoint

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/shared/auth/registration.service.ts
> +        await this.redisClient.set(`pending_registration:${registerDto.number}`, JSON.stringify(cachedData), 'EX', 300);
use the number as a key only, no need to append a reference to it, also consider deleting it after verify, in case the user didn't wait for the 5 min and tried to request a new otp

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/shared/auth/auth.module.ts
> +  controllers: [AuthController,RegistrationController],
since you are adding the Registration as a controller, then it might be useful to move all the controller and the service into the auth module itself

2024-10-04 15:51 UTC, Mahmoudgalalz commented on src/shared/auth/registration.contoller.ts
> +@Controller('auth/registration')
this route is too long, and its not a good practise for RESTful API

we do have an `auth` 
now we have a very saprated `auth/registration` and `auth/registration/register` ! isn't good at all

so as I said above move these into the auth controller it self, and make them, and remove the registration keyword at all

2024-10-04 23:54 UTC, Mahmoudgalalz approved these changes
it has some modification, but its good to go with it @haithamAbuElnasr

2024-10-04 23:54 UTC, merged